ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

# Install Trae AI
COPY ./src/ubuntu/install/trae_ai $INST_SCRIPTS/trae_ai/
RUN bash $INST_SCRIPTS/trae_ai/install_trae_ai.sh && rm -rf $INST_SCRIPTS/trae_ai/

COPY ./src/ubuntu/install/trae_ai/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

COPY ./src/ubuntu/install/trae_ai/vnc_startup.sh /dockerstartup/vnc_startup.sh
RUN chmod 755 /dockerstartup/vnc_startup.sh

COPY ./src/ubuntu/install/trae_ai/ui-BKiQa3b8.js /usr/share/kasmvnc/www/assets/ui-BKiQa3b8.js

RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel

######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV TRAE_WORKDIR ""
ENV KASM_USER kasm-user
ENV HOME /home/kasm-user


ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV TZ=UTC
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
