ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root
ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME
### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/tools/install_tools_deluxe.sh \
                  /ubuntu/install/misc/install_tools.sh \
                  /ubuntu/install/chrome/install_chrome.sh \
                  /ubuntu/install/chromium/install_chromium.sh \
                  /ubuntu/install/vs_code/install_vs_code.sh \
                  /ubuntu/install/vs_code/extensions.sh \
                  /valence/install/python/install_python.sh \
                  /valence/install/python_libraries/install_requirements.sh \
                  /valence/install/labs/ict133.sh \
                  # /valence/install/wallpaper/wallpaper.sh \
                  /ubuntu/install/cleanup/cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR
COPY ./src/valence/install/wallpaper/official_suss_wallpaper.png /usr/share/images/desktop-base/

# Add GitHub PAT as build argument
ARG GITHUB_PAT
ENV PAT=$GITHUB_PAT

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  chmod 644 /usr/share/images/desktop-base/official_suss_wallpaper.png && \
  ln -sf /usr/share/images/desktop-base/official_suss_wallpaper.png /etc/alternatives/desktop-background && \
  unset PAT && \
  unset GITHUB_PAT && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}


# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000
CMD ["--tail-log"]