#!/bin/bash

set -e

browser="$1"
if [[ -z "$browser" ]]; then
  echo "Usage $(basename "$0") <browser_name>"
  echo "  Example: $(basename "$0") edge"
  exit 1
fi

docker build -t kasmweb/"$browser":dev -f dockerfile-kasm-"$browser" .
docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/"$browser":dev
