// User-facing strings — NO technical jargon
export const STRINGS = {
  APP_NAME: "Coeadapt",
  WELCOME_TITLE: "Welcome to Coeadapt",
  WELCOME_SUBTITLE: "Let's get your career workspace set up.",
  SETUP_CHECKING_SYSTEM: "Checking your system...",
  SETUP_DISK_OK: "Storage: Ready",
  SETUP_DISK_LOW: "Your computer needs more free space",
  SETUP_DISK_MINIMUM: "Coeadapt needs at least 15GB of free space.",
  SETUP_DOCKER_CHECKING: "Checking for workspace engine...",
  SETUP_DOCKER_FOUND: "Workspace engine: Ready",
  SETUP_DOCKER_NOT_FOUND:
    "Coeadapt needs to install a small helper app to run your workspace.",
  SETUP_DOCKER_INSTALL: "Install Docker Desktop",
  SETUP_DOCKER_STARTING: "Starting up your workspace engine...",
  SETUP_PULLING: "Downloading your workspace...",
  SETUP_PULLING_SUBTITLE: "This may take a few minutes on first launch (~5GB).",
  SETUP_STARTING: "Starting your workspace...",
  SETUP_READY: "Your workspace is ready!",
  DASHBOARD_RUNNING: "Workspace Running",
  DASHBOARD_STOPPED: "Workspace Stopped",
  DASHBOARD_ERROR: "Something went wrong",
  BTN_OPEN_WORKSPACE: "Open Workspace",
  BTN_START: "Start Workspace",
  BTN_STOP: "Stop Workspace",
  BTN_GET_STARTED: "Get Started",
  BTN_RETRY: "Try Again",
  AI_CONNECTED: "AI Copilot: Connected",
  AI_DISCONNECTED: "AI Copilot: Disconnected",
  MCP_URL: "http://localhost:3100/mcp",
};
